name: "AI Code Commenter"
description: "Automatically reviews pull requests and adds AI-generated comments using OpenAI GPT."
author: "Shresta Voruganti"

inputs:
  openai_api_key:
    description: "Your OpenAI API key"
    required: true
  max_blocks:
    description: "Maximum number of files to review"
    required: false
    default: "5"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    MAX_BLOCKS: ${{ inputs.max_blocks }}

branding:
  icon: "message-square"
  color: "blue"

